spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/account_book?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 12358
#  servlet:
#    session:
#      timeout: 10s

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

logging:
  config: acb_user/src/main/resources/logback.xml

